---
title: "eds-221-day-2-1"
format: html
editor: visual
execute: 
  warning: false
---

## Making and indexing data in R

### Vectors

making vectors

```{r}
dogs <- c("teddy", "khora", "waffle", "bacon", "tito")

# check class of dogs
typeof(dogs)
class(dogs)
```

```{r}
my_breakfast <- c("waffles", 2, TRUE, "coffee")

typeof(my_breakfast)
class(my_breakfast)

```

```{r}
weights <- c(50, 60, 25, 10, 60)

typeof(weights)
class(weights)

# use L to store as integers
weights_integer <- c(50L, 60L, 25L, 10L, 60L)

typeof(weights_integer)
class(weights_integer)
```

```{r}
is.numeric(weights_integer)
```

```{r}
zipcodes <- c(93105, 93514, 93101, 93401)

class(zipcodes)

# use as. family of functions to recast data classes
# use is. family of functions to ASK what class something is
zipcodes_chr <- as.character(zipcodes)

class(zipcodes_chr)
```

## Create a vector with names elements

```{r}
dog_food <- c(teddy = "purina", khora = "alpo", waffle = "fancy feast", bacon = "bluediamond", tito = "farmer's dog")

test <- c(cat = 4, dog = 10, elephant = 11)
class(test)
```

```{r}
dog_food["khora"]
dog_food[2]
# R uses 1-index, first element of index is giving 1
# Python and JavaScript use 0-indexing
```

Access ranges of values in a vector

Use : to refer to a range (low : high)

```{r}
trees <- c("ponderosa", "lodgepole", "jeffrey", "sugar", "white", "bristlecone")

trees[3]

trees[3:5]
```

## Warm-up for for loops

```{r}
i <- 3
trees[i]
```

```{r}
i <- seq(1:3) # same thing as seq(from = 1, to = 3)
yoda <- 4
trees[i]
trees[yoda]
```

```{r}
# reassign value based on position
trees[3] <- "OAK"

trees
```

## Matrix indexing

```{r}
fish_size <- matrix(c(0.8, 1.2, 0.4, 0.9), ncol = 2, nrow = 2, byrow = FALSE)

class(fish_size)
str(fish_size)
typeof(fish_size)

fish_size[ , 2]
```

change document

```{r}
urchins <- list(color = "blue", values = c(1,2,3), meal = c("lunch", "dinner", "dessert"), cost = 5L)

urchins_list <- urchins[2]

urchins_vector <- urchins[[2]]
```

```{r}
urchins$values
```

```{r}
sample1 <- c(1,2,3,4,5,3,2,4,1)
sample2 <- c(3,4,1,6,7,4,8,6,10,11)

ttest_example <- t.test(sample1, sample2)

ttest_example
```

```{r}
class(ttest_example)

ttest_example$p.value
```

Mean size for trees in Site A is greater than the mean size in site B (...my statistical summary, `r ttest_example$p.value`)
